### ISSUE TITLE
Runtime error on import when used with conda-forge graphviz (macOS)

### ISSUE THREAD

**Issue by jayqi** [conda-forge/pygraphviz-feedstock#17]
On macOS and Python 3.8.6, when I install both `pygraphviz` and `graphviz` through conda-forge, I get the following error when trying to use pygraphviz. 

```
>>> import pygraphviz as pgv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jqi/miniconda3/lib/python3.8/site-packages/pygraphviz/__init__.py", line 24, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/Users/jqi/miniconda3/lib/python3.8/site-packages/pygraphviz/agraph.py", line 15, in <module>
    from . import graphviz as gv
  File "/Users/jqi/miniconda3/lib/python3.8/site-packages/pygraphviz/graphviz.py", line 13, in <module>
    from . import _graphviz
ImportError: dlopen(/Users/jqi/miniconda3/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/graphviz/lib/libcdt.5.dylib
  Referenced from: /Users/jqi/miniconda3/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so
  Reason: image not found
```

```
  graphviz           conda-forge/osx-64::graphviz-2.42.3-h055b950_2
  pygraphviz         conda-forge/osx-64::pygraphviz-1.7-py38hfe84aab_0
```

If I separately install graphviz (this ends up being 2.46.0) through homebrew and install only pygraphviz through conda, I am able to load and use pygraphviz with no problems.

**Comment by dschult** [comment]
It would be great to have conda-forge get graphviz 2.46 up and running.
 
We at pygraphviz were having trouble getting our CI to load graphviz on Windows correctly and we worked with the graphviz folks to get that working. I believe that will/should make it easier for conda-forge to get 2.46 working across installations than it has been with previous versions.

Thanks for this!

**Comment by nehaljwani** [comment]
@jayqi Your issue is not reproducible:

```
$ conda create -yp ./dev -c conda-forge pygraphviz python=3.8

$ conda activate ./dev

$ conda list graphviz
# packages in environment at /private/tmp/scratch.nwani/1613259967/dev:
#
# Name                    Version                   Build  Channel
graphviz                  2.42.3               h055b950_2    conda-forge
pygraphviz                1.7              py38hfe84aab_0    conda-forge

$ otool -L ./dev/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so 
./dev/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so:
	@rpath/libcgraph.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/libgvc.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

$ otool -L ./dev/lib/libcgraph.6.dylib 
./dev/lib/libcgraph.6.dylib:
	@rpath/libcgraph.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/libcdt.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

$ python
Python 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:22:12)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygraphviz as pgv
>>>
[1]  + 27483 suspended  python

$ vmmap 27483 | grep libcdt | awk '{print $NF}' | sort -u 
/tmp/scratch.nwani/1613259967/dev/lib/libcdt.5.dylib
```
As you can see, the import works fine and it picks up `libcdt.5.dylib` from the environment prefix.

I would suggest you to check if you have `DYLD_LIBRARY_PATH` set to `/usr/local/opt/graphviz/lib`

**Comment by nehaljwani** [comment]
@dschult Please chime in for discussions on Windows support at https://github.com/conda-forge/pygraphviz-feedstock/issues/13

**Comment by jayqi** [comment]
Thanks for taking a look @nehaljwani. It looks like you're right that I may have had some kind of bad environment state. I'm trying again in fresh environments now and no longer reproducing the error. It's possible that uninstalling and reinstalling graphviz via homebrew or starting a fresh shell session may have fixed whatever the problem was previously. Thank you for your help, and sorry for the false alarm.
